version: '3.8'
services:
  postgres_db:
    container_name: postgres_db1
    build:
      context: ./.docker/postgres
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  apache:
    build: ./.docker/apache
    ports:
      - 8080:80
    volumes:
      - ./public:/var/www/html/public:ro
      - ./.docker/apache/config/vhosts.conf:/etc/apache2/sites-enabled/vhosts.conf:ro
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    environment:
      APP_ENV: ${APP_ENV}
    volumes:
      - .:/var/www/html:rw
      - ./.docker/php/logs:/app/var/logs:rw