version: '3.8'
services:
  apache:
    build: ./.docker/apache
    ports:
      - 8080:80
    volumes:
      - ./public:/var/www/html/public:ro
      - ./.docker/apache/config/vhosts.conf:/etc/apache2/sites-enabled/vhosts.conf:ro
    depends_on:
      - php
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    environment:
      APP_ENV: ${APP_ENV}
    volumes:
      - .:/var/www/html:rw
      - ./.docker/php/logs:/app/var/logs:rw
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
